namespace Sucrose.Shared.Dependency.Enum
{
    /// <summary>
    /// 
    /// </summary>
    public enum CompatibilityType
    {
        Pass,
        Tags,
        Type,
        Title,
        Author,
        Source,
        Contact,
        Preview,
        Encrypt,
        ZipType,
        InfoFile,
        NotFound,
        LoopMode,
        Arguments,
        Extension,
        Thumbnail,
        SystemCpu,
        EmptyInfo,
        AppVersion,
        InvalidUrl,
        SystemBios,
        SystemDate,
        SystemAudio,
        Description,
        InvalidInfo,
        TriggerTime,
        StretchMode,
        VolumeLevel,
        ShuffleMode,
        InvalidTags,
        InvalidFile,
        PropertyList,
        SystemMemory,
        SystemBattery,
        SystemGraphic,
        SystemNetwork,
        InvalidContact,
        EmptyCompatible,
        EmptyProperties,
        InvalidExtension,
        PropertyListener,
        SystemMotherboard,
        InvalidCompatible,
        InvalidProperties,
        UnforeseenConsequences
    }
}